FROM ubuntu:16.04

MAINTAINER XuanSon <xuansonitvn@gmail.com>

LABEL maintainer="XuanSon <xuansonitvn@gmail.com>" \
	org.label-schema.name="Ubuntu 16.04 with redis" 
LABEL version="1.0"

# Set time asia/ho_chi_minh
RUN cp /usr/share/zoneinfo/Asia/Ho_Chi_Minh /etc/localtime